KREG-3: Do not reject requests with undefined user-agent
2600hz/kazoo-registrar pull request #20
Opened 2022-11-11 01:33 UTC by harenson

Also:
- Fix bug and make ?INTEGRATION_DEVICE_TYPES list configurable.
Fix a bug because ?INTEGRATION_DEVICE_TYPES macro was returning an
static value, and that value would never match the chosen device type
for MS Teams integration, "teammate". So, checks were being skipped in
maybe_perform_integration_device_checks/3, because the device type,
"teammate", was not listed as an integration device type.
- Fix subscribe requests being rejected because they don't include a user-agent (Found by @lazedo ).
- Improve code comments and future log lines.
- Move migration functionality to core/kazoo_endpoint application.

Depends on:
- https://github.com/2600hz/kazoo-crossbar/pull/380

2022-11-13 12:35 UTC, lazedo requested changes

2022-11-13 12:35 UTC, lazedo commented on src/reg_authn_req.erl
> +    %% UAs don't send user-agent for subscribe requests.
remove personal references

2022-11-13 12:35 UTC, lazedo commented on src/reg_authn_req.erl
>  maybe_migrate_softphone_to_ms_teams({'ok', _AuthUser} = Ret, UserAgent, 'true') ->
this should be moved outside of this repo, we shouldn't be handling exception and migrations here

2022-11-15 18:11 UTC, harenson commented on src/reg_authn_req.erl
>  maybe_migrate_softphone_to_ms_teams({'ok', _AuthUser} = Ret, UserAgent, 'true') ->
@lazedo Which repository do you suggest to move this functionality into?

2022-11-15 18:37 UTC, harenson commented on src/reg_authn_req.erl
>  maybe_migrate_softphone_to_ms_teams({'ok', _AuthUser} = Ret, UserAgent, 'true') ->
Is it ok for you to move this migration functionality into _registrar_maintenance.erl_ module?

2022-11-15 21:48 UTC, harenson commented on src/reg_authn_req.erl
> +    %% UAs don't send user-agent for subscribe requests.
Done.

2022-11-15 21:49 UTC, harenson commented on src/reg_authn_req.erl
>  maybe_migrate_softphone_to_ms_teams({'ok', _AuthUser} = Ret, UserAgent, 'true') ->
I moved the migration process to core/kazoo_endpoint application, the check to know if it needs to be migrated or not is still in registrar because this automatic migration is a temporary functionality, it will be removed in the future.

2022-11-15 21:53 UTC, lazedo requested changes

2022-11-15 21:53 UTC, lazedo commented on src/reg_authn_req.erl
> +    %% user-agent for subscribe requests.
remove this, `User-Agent` is `not` a required `header`. its not specific to any method and its up to UA by configuration or capability to send it or not

2022-11-15 21:56 UTC, harenson commented on src/reg_authn_req.erl
> +    %% user-agent for subscribe requests.
Done.

2022-11-22 18:04 UTC, lazedo approved these changes

2022-11-23 18:46 UTC, merged